// Generated by CoffeeScript 1.6.3
(function() {
  var qs;

  qs = function(arr) {
    var i;
    if (arr.length <= 1) {
      return arr;
    }
    return [].concat(qs((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = arr.length; _i < _len; _i++) {
        i = arr[_i];
        if (i < arr[0]) {
          _results.push(i);
        }
      }
      return _results;
    })()), [arr[0]], qs((function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = arr.length; _i < _len; _i++) {
        i = arr[_i];
        if (i > arr[0]) {
          _results.push(i);
        }
      }
      return _results;
    })()));
  };

  module.exports = qs;

}).call(this);
