// Generated by CoffeeScript 1.6.2
(function() {
  var deep, funcster, vm, _,
    __slice = [].slice;

  _ = require('underscore');

  vm = require('vm');

  deep = require('deep');

  funcster = {
    serialize: function(func, marker) {
      var wrapper;

      if (marker == null) {
        marker = '__js_function';
      }
      wrapper = {};
      wrapper[marker] = func.toString();
      return wrapper;
    },
    deepSerialize: function(root, marker) {
      if (marker == null) {
        marker = '__js_function';
      }
      return deep.transform(root, _.isFunction, function(func) {
        return funcster.serialize(func, marker);
      });
    },
    deepDeserialize: function() {
      var extraArgs, f, functions, functionsByName, marker, moduleContent, moduleObj, moduleOpts, root, _i, _j, _k, _len, _len1, _len2;

      root = arguments[0], extraArgs = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      switch (extraArgs.length) {
        case 0:
          marker = '__js_function';
          moduleOpts = {};
          break;
        case 1:
          if (_.isString(extraArgs[0])) {
            marker = extraArgs[0];
            moduleOpts = {};
          } else {
            marker = '__js_function';
            moduleOpts = extraArgs[0];
          }
          break;
        default:
          marker = extraArgs[0];
          moduleOpts = extraArgs[1];
      }
      root = deep.clone(root);
      functions = this._deepSelectSerializations(root, marker);
      for (_i = 0, _len = functions.length; _i < _len; _i++) {
        f = functions[_i];
        f.name = "func_" + f.path.join('_');
      }
      functionsByName = {};
      for (_j = 0, _len1 = functions.length; _j < _len1; _j++) {
        f = functions[_j];
        functionsByName[f.name] = f.value[marker];
      }
      moduleContent = this._generateModuleScript(functionsByName);
      moduleObj = this._generateModule(moduleContent, moduleOpts);
      for (_k = 0, _len2 = functions.length; _k < _len2; _k++) {
        f = functions[_k];
        if (!f.path.length) {
          return moduleObj[f.name];
        }
        deep.set(root, f.path, moduleObj[f.name]);
      }
      return root;
    },
    _deepSelectSerializations: function(root, marker) {
      if (marker == null) {
        marker = '__js_function';
      }
      return deep.select(root, function(obj) {
        return _.isObject(obj) && _.isString(obj[marker]);
      });
    },
    _generateModuleScript: function(serializedFunctions) {
      var body, entries, name;

      entries = [];
      for (name in serializedFunctions) {
        body = serializedFunctions[name];
        entries.push("" + name + ": " + body);
      }
      entries = entries.join(',');
      return "module.exports=(function(global,module,exports){return{" + entries + "};})();";
    },
    _generateModule: function(content, opts) {
      var exportsObj, globals, k, sandbox, v;

      if (opts == null) {
        opts = {};
      }
      sandbox = {};
      exportsObj = {};
      sandbox.global = sandbox;
      sandbox.exports = exportsObj;
      sandbox.module = {
        exports: exportsObj
      };
      globals = opts.globals || {};
      for (k in globals) {
        v = globals[k];
        sandbox.global[k] = v;
      }
      vm.createScript(content, opts.filename).runInNewContext(sandbox);
      return sandbox.module.exports;
    }
  };

  module.exports = funcster;

}).call(this);
